type Loader = () => Promise<{ default: (req: any, res: any) => any }>;

export const legacyManifest: Record<string, Record<string, Loader>> = {
  auth: {
    'admin/aadhaar': () => import('../legacy_api/auth/admin/aadhaar'),
    'admin/aadhaar-signin': () => import('../legacy_api/auth/admin/aadhaar-signin'),
    'admin/biometric': () => import('../legacy_api/auth/admin/biometric'),
    'admin/profiles': () => import('../legacy_api/auth/admin/profiles'),
    'admin/signin': () => import('../legacy_api/auth/admin/signin'),
    'admin/signup': () => import('../legacy_api/auth/admin/signup'),
    'profile/[partnerId]': () => import('../legacy_api/auth/profile/[partnerId]'),
    'register-password': () => import('../legacy_api/auth/register-password'),
    'register-user': () => import('../legacy_api/auth/register-user'),
    'verify-password': () => import('../legacy_api/auth/verify-password'),
    'webauthn/generate-authentication-options': () => import('../legacy_api/auth/webauthn/generate-authentication-options'),
    'webauthn/generate-registration-options': () => import('../legacy_api/auth/webauthn/generate-registration-options'),
    'webauthn/verify-authentication': () => import('../legacy_api/auth/webauthn/verify-authentication'),
    'webauthn/verify-registration': () => import('../legacy_api/auth/webauthn/verify-registration'),
    'worker/register-password': () => import('../legacy_api/auth/worker/register-password'),
    'worker/register-user': () => import('../legacy_api/auth/worker/register-user'),
    'worker/verify-password': () => import('../legacy_api/auth/worker/verify-password'),
  },
  admin: {
    'audit-trace': () => import('../legacy_api/admin/audit-trace'),
    'auth/aadhaar-fallback': () => import('../legacy_api/admin/auth/aadhaar-fallback'),
    'auth/aadhaar-signin': () => import('../legacy_api/admin/auth/aadhaar-signin'),
    'auth/profiles': () => import('../legacy_api/admin/auth/profiles'),
    'auth/register-biometric': () => import('../legacy_api/admin/auth/register-biometric'),
    'auth/signin': () => import('../legacy_api/admin/auth/signin'),
    'auth/signup': () => import('../legacy_api/admin/auth/signup'),
    'auth/health': () => import('../legacy_api/admin/auth/health'),
    'fraud-mesh': () => import('../legacy_api/admin/fraud-mesh'),
    'guidewire-export': () => import('../legacy_api/admin/guidewire-export'),
    'news': () => import('../legacy_api/admin/news'),
    'ops-freshness': () => import('../legacy_api/admin/ops-freshness'),
    'partner-analytics': () => import('../legacy_api/admin/partner-analytics'),
    'product-controls': () => import('../legacy_api/admin/product-controls'),
    'recent-claims': () => import('../legacy_api/admin/recent-claims'),
    'claim/resolve': () => import('../legacy_api/admin/claim/resolve'),
    'reinsurance-cat': () => import('../legacy_api/admin/reinsurance-cat'),
    'reserve/projection': () => import('../legacy_api/admin/reserve/projection'),
    'riders': () => import('../legacy_api/admin/riders'),
    'risk/action': () => import('../legacy_api/admin/risk/action'),
    'risk-alerts': () => import('../legacy_api/admin/risk-alerts'),
    'risk-distribution': () => import('../legacy_api/admin/risk-distribution'),
    'sensor-fusion': () => import('../legacy_api/admin/sensor-fusion'),
    'simulate': () => import('../legacy_api/admin/simulate'),
    'simulations/scenario': () => import('../legacy_api/admin/simulations/scenario'),
    'stats': () => import('../legacy_api/admin/stats'),
    'workers/locations': () => import('../legacy_api/admin/workers/locations'),
  },
  user: {
    'device-state': () => import('../legacy_api/user/device-state'),
    'inbox': () => import('../legacy_api/user/inbox'),
    'latest-payout': () => import('../legacy_api/user/latest-payout'),
    'location': () => import('../legacy_api/user/location'),
    'notifications/register': () => import('../legacy_api/user/notifications/register'),
    'simulation-signal': () => import('../legacy_api/user/simulation-signal'),
    'state': () => import('../legacy_api/user/state'),
    'sync': () => import('../legacy_api/user/sync'),
    'sync/balance': () => import('../legacy_api/user/sync/balance'),
    'sync/claim': () => import('../legacy_api/user/sync/claim'),
    'sync/transaction': () => import('../legacy_api/user/sync/transaction'),
    'trust-passport': () => import('../legacy_api/user/trust-passport'),
    'update-payment-methods': () => import('../legacy_api/user/update-payment-methods'),
    'update-plan': () => import('../legacy_api/user/update-plan'),
  },
  claims: {
    'create': () => import('../legacy_api/claims/create'),
    'dispute': () => import('../legacy_api/claims/dispute'),
    'explain/[claimId]': () => import('../legacy_api/claims/explain/[claimId]'),
    'time-shifted': () => import('../legacy_api/claims/time-shifted'),
    'verify-all': () => import('../legacy_api/claims/verify-all'),
  },
  finance: {
    'actuarial/inputs': () => import('../legacy_api/actuarial/inputs'),
    'actuarial/pmax': () => import('../legacy_api/actuarial/pmax'),
    'actuarial/revenue-projection': () => import('../legacy_api/actuarial/revenue-projection'),
    'payments/razorpay': () => import('../legacy_api/payments/razorpay'),
    'premium/activate': () => import('../legacy_api/premium/activate'),
    'razorpay/create-order': () => import('../legacy_api/razorpay/create-order'),
    'razorpay/create-subscription': () => import('../legacy_api/razorpay/create-subscription'),
    'wallet/update': () => import('../legacy_api/wallet/update'),
  },
  intelligence: {
    'ai/risk-insights': () => import('../legacy_api/ai/risk-insights'),
    'ai/voice-explainer': () => import('../legacy_api/ai/voice-explainer'),
    'aqi': () => import('../legacy_api/aqi'),
    'delhi-protocol': () => import('../legacy_api/intelligence/delhi-protocol'),
    'ml/calculate-premium': () => import('../legacy_api/ml/calculate-premium'),
    'traffic': () => import('../legacy_api/traffic'),
    'verify/device-trust': () => import('../legacy_api/verify/device-trust'),
    'verify/forecast': () => import('../legacy_api/verify/forecast'),
    'verify/multivariate-pulse': () => import('../legacy_api/verify/multivariate-pulse'),
    'vision-parse': () => import('../legacy_api/intelligence/vision-parse'),
    'weather': () => import('../legacy_api/weather'),
  },
  system: {
    'cron/auto-trigger': () => import('../legacy_api/cron/auto-trigger'),
    'cron/predictive-shield': () => import('../legacy_api/cron/predictive-shield'),
    'crowd-consensus': () => import('../legacy_api/system/crowd-consensus'),
    'health': () => import('../legacy_api/system/health'),
  },
};

