type Loader = () => Promise<{ default: (req: any, res: any) => any }>;

export const legacyManifest: Record<string, Record<string, Loader>> = {
  auth: {
    'admin/aadhaar': () => import('../legacy_api/auth/admin/aadhaar.ts'),
    'admin/aadhaar-signin': () => import('../legacy_api/auth/admin/aadhaar-signin.ts'),
    'admin/biometric': () => import('../legacy_api/auth/admin/biometric.ts'),
    'admin/profiles': () => import('../legacy_api/auth/admin/profiles.ts'),
    'admin/signin': () => import('../legacy_api/auth/admin/signin.ts'),
    'admin/signup': () => import('../legacy_api/auth/admin/signup.ts'),
    'profile/[partnerId]': () => import('../legacy_api/auth/profile/[partnerId].ts'),
    'register-password': () => import('../legacy_api/auth/register-password.ts'),
    'register-user': () => import('../legacy_api/auth/register-user.ts'),
    'verify-password': () => import('../legacy_api/auth/verify-password.ts'),
    'webauthn/generate-authentication-options': () => import('../legacy_api/auth/webauthn/generate-authentication-options.ts'),
    'webauthn/generate-registration-options': () => import('../legacy_api/auth/webauthn/generate-registration-options.ts'),
    'webauthn/verify-authentication': () => import('../legacy_api/auth/webauthn/verify-authentication.ts'),
    'webauthn/verify-registration': () => import('../legacy_api/auth/webauthn/verify-registration.ts'),
    'worker/register-password': () => import('../legacy_api/auth/worker/register-password.ts'),
    'worker/register-user': () => import('../legacy_api/auth/worker/register-user.ts'),
    'worker/verify-password': () => import('../legacy_api/auth/worker/verify-password.ts'),
  },
  admin: {
    'audit-trace': () => import('../legacy_api/admin/audit-trace.ts'),
    'auth/aadhaar-fallback': () => import('../legacy_api/admin/auth/aadhaar-fallback.ts'),
    'auth/aadhaar-signin': () => import('../legacy_api/admin/auth/aadhaar-signin.ts'),
    'auth/profiles': () => import('../legacy_api/admin/auth/profiles.ts'),
    'auth/register-biometric': () => import('../legacy_api/admin/auth/register-biometric.ts'),
    'auth/signin': () => import('../legacy_api/admin/auth/signin.ts'),
    'auth/signup': () => import('../legacy_api/admin/auth/signup.ts'),
    'auth/health': () => import('../legacy_api/admin/auth/health.ts'),
    'fraud-mesh': () => import('../legacy_api/admin/fraud-mesh.ts'),
    'guidewire-export': () => import('../legacy_api/admin/guidewire-export.ts'),
    'news': () => import('../legacy_api/admin/news.ts'),
    'ops-freshness': () => import('../legacy_api/admin/ops-freshness.ts'),
    'partner-analytics': () => import('../legacy_api/admin/partner-analytics.ts'),
    'product-controls': () => import('../legacy_api/admin/product-controls.ts'),
    'recent-claims': () => import('../legacy_api/admin/recent-claims.ts'),
    'claim/resolve': () => import('../legacy_api/admin/claim/resolve.ts'),
    'reinsurance-cat': () => import('../legacy_api/admin/reinsurance-cat.ts'),
    'reserve/projection': () => import('../legacy_api/admin/reserve/projection.ts'),
    'riders': () => import('../legacy_api/admin/riders.ts'),
    'risk/action': () => import('../legacy_api/admin/risk/action.ts'),
    'risk-alerts': () => import('../legacy_api/admin/risk-alerts.ts'),
    'risk-distribution': () => import('../legacy_api/admin/risk-distribution.ts'),
    'sensor-fusion': () => import('../legacy_api/admin/sensor-fusion.ts'),
    'simulate': () => import('../legacy_api/admin/simulate.ts'),
    'simulations/scenario': () => import('../legacy_api/admin/simulations/scenario.ts'),
    'stats': () => import('../legacy_api/admin/stats.ts'),
    'workers/locations': () => import('../legacy_api/admin/workers/locations.ts'),
  },
  user: {
    'device-state': () => import('../legacy_api/user/device-state.ts'),
    'inbox': () => import('../legacy_api/user/inbox.ts'),
    'latest-payout': () => import('../legacy_api/user/latest-payout.ts'),
    'location': () => import('../legacy_api/user/location.ts'),
    'notifications/register': () => import('../legacy_api/user/notifications/register.ts'),
    'simulation-signal': () => import('../legacy_api/user/simulation-signal.ts'),
    'state': () => import('../legacy_api/user/state.ts'),
    'sync': () => import('../legacy_api/user/sync.ts'),
    'sync/balance': () => import('../legacy_api/user/sync/balance.ts'),
    'sync/claim': () => import('../legacy_api/user/sync/claim.ts'),
    'sync/transaction': () => import('../legacy_api/user/sync/transaction.ts'),
    'trust-passport': () => import('../legacy_api/user/trust-passport.ts'),
    'update-payment-methods': () => import('../legacy_api/user/update-payment-methods.ts'),
    'update-plan': () => import('../legacy_api/user/update-plan.ts'),
  },
  claims: {
    'create': () => import('../legacy_api/claims/create.ts'),
    'dispute': () => import('../legacy_api/claims/dispute.ts'),
    'explain/[claimId]': () => import('../legacy_api/claims/explain/[claimId].ts'),
    'time-shifted': () => import('../legacy_api/claims/time-shifted.ts'),
    'verify-all': () => import('../legacy_api/claims/verify-all.ts'),
  },
  finance: {
    'actuarial/inputs': () => import('../legacy_api/actuarial/inputs.ts'),
    'actuarial/pmax': () => import('../legacy_api/actuarial/pmax.ts'),
    'actuarial/revenue-projection': () => import('../legacy_api/actuarial/revenue-projection.ts'),
    'payments/razorpay': () => import('../legacy_api/payments/razorpay.ts'),
    'premium/activate': () => import('../legacy_api/premium/activate.ts'),
    'razorpay/create-order': () => import('../legacy_api/razorpay/create-order.ts'),
    'razorpay/create-subscription': () => import('../legacy_api/razorpay/create-subscription.ts'),
    'wallet/update': () => import('../legacy_api/wallet/update.ts'),
  },
  intelligence: {
    'ai/risk-insights': () => import('../legacy_api/ai/risk-insights.ts'),
    'ai/voice-explainer': () => import('../legacy_api/ai/voice-explainer.ts'),
    'aqi': () => import('../legacy_api/aqi.ts'),
    'delhi-protocol': () => import('../legacy_api/intelligence/delhi-protocol.ts'),
    'ml/calculate-premium': () => import('../legacy_api/ml/calculate-premium.ts'),
    'traffic': () => import('../legacy_api/traffic.ts'),
    'verify/device-trust': () => import('../legacy_api/verify/device-trust.ts'),
    'verify/forecast': () => import('../legacy_api/verify/forecast.ts'),
    'verify/multivariate-pulse': () => import('../legacy_api/verify/multivariate-pulse.ts'),
    'vision-parse': () => import('../legacy_api/intelligence/vision-parse.ts'),
    'weather': () => import('../legacy_api/weather.ts'),
  },
  system: {
    'cron/auto-trigger': () => import('../legacy_api/cron/auto-trigger.ts'),
    'cron/predictive-shield': () => import('../legacy_api/cron/predictive-shield.ts'),
    'crowd-consensus': () => import('../legacy_api/system/crowd-consensus.ts'),
    'health': () => import('../legacy_api/system/health.ts'),
  },
};
